import { Entry } from "@/lib/types";

export const placeholderEntries: Entry[] = [
  {
    id: "1",
    type: "milestone",
    title: "Corp Founded",
    body: "A handful of pilots tired of null-sec blues formed the corp, chasing something more permanent than a fleet of the week.",
    event_date: "2019-01-01",
    date_precision: "year",
    author_id: "user_founder",
    author_name: "Aria Voss",
    status: "approved",
    created_at: "2019-01-01T00:00:00.000Z",
    updated_at: "2019-01-01T00:00:00.000Z",
  },
  {
    id: "2",
    type: "story",
    title: "How I Became a Miner",
    body: "I joined thinking I'd fly frigates all day. Three months later I owned two Hulks and could recite ore prices from memory. No regrets.",
    event_date: "2019-06-01",
    date_precision: "year",
    author_id: "user_miner",
    author_name: "Denks Okonkwo",
    status: "approved",
    created_at: "2019-06-01T00:00:00.000Z",
    updated_at: "2019-06-01T00:00:00.000Z",
  },
  {
    id: "3",
    type: "milestone",
    title: "First Null-Sec System Secured",
    body: "After months of renting, we took and held our own system. The first Sotiyo went up a week later and we haven't looked back since.",
    event_date: "2020-03-01",
    date_precision: "month",
    author_id: "user_founder",
    author_name: "Aria Voss",
    status: "approved",
    created_at: "2020-03-01T00:00:00.000Z",
    updated_at: "2020-03-01T00:00:00.000Z",
  },
  {
    id: "4",
    type: "story",
    title: "My First Fleet Fight",
    body: "FC said 'form up, T1 cruisers, no questions.' I lost my first ship in ninety seconds flat and immediately reshipped. Best isk I ever spent.",
    event_date: "2020-11-14",
    date_precision: "day",
    author_id: "user_newbro",
    author_name: "Toma Reyes",
    status: "approved",
    created_at: "2020-11-14T00:00:00.000Z",
    updated_at: "2020-11-14T00:00:00.000Z",
  },
  {
    id: "5",
    type: "milestone",
    title: "The Great Wormhole Relocation",
    body: "Sov war losses forced a full corp move into a C5 wormhole. It was meant to be temporary. We're still there.",
    event_date: "2022-08-01",
    date_precision: "month",
    author_id: "user_logistics",
    author_name: "Priya Nakamura",
    status: "approved",
    created_at: "2022-08-01T00:00:00.000Z",
    updated_at: "2022-08-01T00:00:00.000Z",
  },
  {
    id: "6",
    type: "milestone",
    title: "Alliance Merger with Ashen Concord",
    body: "Formal merger talks concluded after two months of joint ops. Pending officer sign-off before it goes on the record.",
    event_date: "2026-06-02",
    date_precision: "day",
    author_id: "user_founder",
    author_name: "Aria Voss",
    status: "pending",
    created_at: "2026-06-02T00:00:00.000Z",
    updated_at: "2026-06-02T00:00:00.000Z",
  },
];
