import { Entry } from "@/lib/types";

export const placeholderEntries: Entry[] = [
  {
    id: "1",
    type: "milestone",
    title: "Основание корпорации",
    body: "Горстка пилотов, уставших от вечной нестабильности нул-сека, основала корпорацию, стремясь к чему-то более постоянному, чем флот на один вечер.",
    event_date: "2019-01-01",
    date_precision: "year",
    author_id: "user_founder",
    author_name: "Ария Восс",
    status: "approved",
    created_at: "2019-01-01T00:00:00.000Z",
    updated_at: "2019-01-01T00:00:00.000Z",
  },
  {
    id: "2",
    type: "story",
    title: "Как я стал шахтёром",
    body: "Вступал, думая, что буду летать на фрегатах днями напролёт. Три месяца спустя у меня было два Hulk'а, и я знал цены на руду наизусть. Ни капли не жалею.",
    event_date: "2019-06-01",
    date_precision: "year",
    author_id: "user_miner",
    author_name: "Денис Оконкво",
    status: "approved",
    created_at: "2019-06-01T00:00:00.000Z",
    updated_at: "2019-06-01T00:00:00.000Z",
  },
  {
    id: "3",
    type: "milestone",
    title: "Закреплена первая система в нул-секе",
    body: "После месяцев аренды мы захватили и удержали собственную систему. Первый Sotiyo встал уже через неделю, и с тех пор мы не оглядывались назад.",
    event_date: "2020-03-01",
    date_precision: "month",
    author_id: "user_founder",
    author_name: "Ария Восс",
    status: "approved",
    created_at: "2020-03-01T00:00:00.000Z",
    updated_at: "2020-03-01T00:00:00.000Z",
  },
  {
    id: "4",
    type: "story",
    title: "Мой первый флотовый бой",
    body: "ФК сказал: «Строимся, крейсера первого тира, без вопросов». Я потерял свой первый корабль за девяносто секунд и тут же пересел на новый. Лучшие потраченные исковые.",
    event_date: "2020-11-14",
    date_precision: "day",
    author_id: "user_newbro",
    author_name: "Тома Рейес",
    status: "approved",
    created_at: "2020-11-14T00:00:00.000Z",
    updated_at: "2020-11-14T00:00:00.000Z",
  },
  {
    id: "5",
    type: "milestone",
    title: "Великое переселение в червоточину",
    body: "Потери в войне за суверенитет вынудили корпорацию полностью переехать в червоточину класса C5. Планировалось, что это временно. Мы там до сих пор.",
    event_date: "2022-08-01",
    date_precision: "month",
    author_id: "user_logistics",
    author_name: "Прия Накамура",
    status: "approved",
    created_at: "2022-08-01T00:00:00.000Z",
    updated_at: "2022-08-01T00:00:00.000Z",
  },
  {
    id: "6",
    type: "milestone",
    title: "Слияние с альянсом «Пепельное согласие»",
    body: "Официальные переговоры о слиянии завершились после двух месяцев совместных операций. Ожидает одобрения офицеров, прежде чем попасть в летопись.",
    event_date: "2026-06-02",
    date_precision: "day",
    author_id: "user_founder",
    author_name: "Ария Восс",
    status: "pending",
    created_at: "2026-06-02T00:00:00.000Z",
    updated_at: "2026-06-02T00:00:00.000Z",
  },
];
